back_end/_02_django_templates/_02_django_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='app/')),
    path('app/', include('app.urls')),
]

back_end/_02_django_templates/app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('basics/', views.basics, name='basics'),
    path('layout/', views.layout, name='layout'),
    path('staticfiles/', views.staticfiles, name='staticfiles'),
    path('urls/', views.urls, name='urls'),
    path('product/<int:id>', views.product, name='product'),
    path('search/', views.search, name='search'),
]

back_end/_02_django_templates/app/models.py
from django.db import models

# Create your models here.

back_end/_02_django_templates/app/views.py
from django.shortcuts import render
from datetime import datetime

def index(request):
    return render(request, 'app/index.html')

def basics(request):
    context = {
        "name": "코난",
        "job": "탐정",
        "height": 150,
        "hobby": ["추리하기", "사건 쫓아다니기", "탐정님 재우기"],
        "today": datetime.now(),
        "users": [
            {"id": 1, "name": "뭉치", "study": False},
            {"id": 2, "name": "세모", "study": True},
            {"id": 3, "name": "아름", "study": True},
        ],
        "users": [],
        "eng_name": "conan",
        "price": 12345.6789
    }
    return render(request, 'app/01_basics.html', context)

def layout(request):
    return render(request, 'app/02_layout.html')

def staticfiles(request):
    return render(request, 'app/03_staticfiles.html')

def urls(request):
    return render(request, 'app/04_urls.html')

def product(request, id):
    print('@@@@@ product id [path variable] @@@@@', id)
    return render(request, 'app/04_urls.html')

def search(request):
    print(request.GET)
    # q = request.GET.get('q')
    # lang = request.GET.get('lang')
    # return render(request, 'app/04_urls.html', {'q': q, 'lang': lang})
    return render(request, 'app/04_urls.html')

back_end/_02_django_templates/templates/app/01_basics.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load humanize %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>templates | Basics</title>
    <style>
        table {
            border: 1px solid #000;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #000;
            padding: 5px;
        }
    </style>
</head>
<body>
    <h1>Django Templates: Basics</h1>

    <!-- html 주석 -->
    {# template 한 줄 주석 #}
    {% comment %}
        template
        여러 줄 주석
        따란!
    {% endcomment %}

    <h3>Variables</h3>
    {# views 함수에서 전달한 변수 출력 가능 #}
    <p>내 이름은 {{ name }},</p>
    <p>{{ job }} 이죠.</p>

    <h3>Statements</h3>
    <h5>조건 처리</h5>
    {# if, elif, else, ..., endif #}
    {% if height > 180 %}
        <p>어른</p>
    {% else %}
        <p>어린이</p>
    {% endif %}

    <h5>반복 처리</h5>
    {# for-in, endfor #}
    <ul>
        {% for h in hobby %}
            <li>{{ h }}</li>
        {% endfor %}
    </ul>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>NAME</th>
                <th>Study Hard</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.name }}</td>
                    <td>
                        <input type="checkbox" {% if user.study %}checked{% endif %}/>
                    </td>
                </tr>
                {% empty %} {# 반복 처리할 대상이 없는 경우 동작 #}
                    <tr>
                        <td colspan="3">멤버가 존재하지 않습니다.</td>
                    </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Filter</h3>
    {# 변수 후처리를 지원하는 표현식 #}
    <ul>
        <li>가격: {{ price|floatformat:2 }}원</li>
        <li>가격: {{ price|intcomma }}원</li>
        <li>자고 일어났더니 키가 컸어! 내 키는 {{ height|add:2 }}cm 야!!!</li>
        <li>자고 일어났더니 키가 컸어! 내 키는 {{ height|add:2 }}cm 야!!!</li>
        <li>오늘은 {{ today }} 입니다~</li>
        <li>오늘은 {{ today|date:"Y/m/d" }} 입니다~</li>
        <li>오늘은 {{ today|date:"Y/m/d (D) H:i:s" }} 입니다~</li>
        <li>My name is {{ eng_name|upper }}@</li>
        <li>My name is {{ eng_name|length }}@</li>
    </ul>

    <h3>Variable Declaration</h3>
    {% now 'Y' as current_year %}
    <p>올해는 {{ current_year }}년!!!!!</p>

    {% with '순두부찌개' as lunch_menu %}
        <p>오늘 점심 메뉴는 {{ lunch_menu }}로 결정했어!!!!!</p>
    {% endwith %}
</body>
</html>

back_end/_02_django_templates/templates/app/02_layout.html
{% extends 'layout/base.html' %}

{% block title %}Layout{% endblock title %}

{% block content %}
    <h1>Django Templates: Layout</h1>
    <p>도토리 먹을래????? 🌰🐿️</p>
{% endblock content %}

back_end/_02_django_templates/templates/app/03_staticfiles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>templates | StaticFiles</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>Django Templates: Static Files</h1>

    <img src="{% static 'images/squirrel.gif' %}" />
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

back_end/_02_django_templates/templates/app/04_urls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>template | URLs</title>
</head>
<body>
    <h1>Django Templates: URLs</h1>

    <h3>Path Variable</h3>
    <div><a href="{% url 'app:product' id=123 %}">123번 product</a></div>

    <h3>Query String</h3>
    {% comment %}     
    <a href="{% url 'app:search' %}?q={{q}}&lang={{lang}}">
        검색어 {{ q }} | 언어 {{ lang }}
    </a> 
    {% endcomment %} 
    <a href="{% url 'app:search' %}?q={{request.GET.q}}&lang={{request.GET.lang}}">
        검색어 {{ request.GET.q }} | 언어 {{ request.GET.lang }}
    </a> 
</body>
</html>

back_end/_02_django_templates/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App | Index</title>
</head>
<body>
    <h1>Django Templates</h1>

    <ul>
        <li><a href="{% url 'app:basics' %}">Basics</a></li>
        <li><a href="{% url 'app:layout' %}">Layout</a></li>
        <li><a href="{% url 'app:staticfiles' %}">StaticFiles</a></li>
        <li><a href="{% url 'app:urls' %}">URLs</a></li>
    </ul>
</body>
</html>

back_end/_02_django_templates/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>templates | {% block title %}App{% endblock title %}</title>
</head>
<body>
    {% include 'layout/header.html' %}

    <main>
        {% block content %}
        
        {% endblock content %}
    </main>

    {% include 'layout/footer.html' %}
</body>
</html>

back_end/_02_django_templates/templates/layout/footer.html
<footer>
    <h1>🌰squirrel@helloworldlabs.kr🌰</h1>
</footer>

back_end/_02_django_templates/templates/layout/header.html
<header>
    <h1>🐿️다 람 쥐 월 드🐿️</h1>
</header>